name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.11.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install
        env:
          HUSKY: 0

      - name: Type Check
        run: pnpm validate:tsc

      - name: Lint
        run: pnpm validate:lint

      - name: Format Check
        run: pnpm validate:format

      - name: Server Unit Tests
        run: pnpm vitest run --config vitest.server.unit.config.ts --coverage

      - name: Server Integration Tests
        run: pnpm vitest run --config vitest.server.integration.config.ts --coverage

      - name: Upload Coverage
        if: always()
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build
        run: pnpm build
